USE [master]
GO
/****** Object:  Database [SistemaTecnicos]    Script Date: 03/25/2013 20:19:01 ******/
CREATE DATABASE [SistemaTecnicos] ON  PRIMARY 
( NAME = N'SistemaTecnicos', FILENAME = N'D:\SQLServer\Data\SistemaTecnicos.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SistemaTecnicos_log', FILENAME = N'D:\SQLServer\Data\SistemaTecnicos_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [SistemaTecnicos] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SistemaTecnicos].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SistemaTecnicos] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [SistemaTecnicos] SET ANSI_NULLS OFF
GO
ALTER DATABASE [SistemaTecnicos] SET ANSI_PADDING OFF
GO
ALTER DATABASE [SistemaTecnicos] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [SistemaTecnicos] SET ARITHABORT OFF
GO
ALTER DATABASE [SistemaTecnicos] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [SistemaTecnicos] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [SistemaTecnicos] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [SistemaTecnicos] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [SistemaTecnicos] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [SistemaTecnicos] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [SistemaTecnicos] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [SistemaTecnicos] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [SistemaTecnicos] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [SistemaTecnicos] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [SistemaTecnicos] SET  DISABLE_BROKER
GO
ALTER DATABASE [SistemaTecnicos] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [SistemaTecnicos] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [SistemaTecnicos] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [SistemaTecnicos] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [SistemaTecnicos] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [SistemaTecnicos] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [SistemaTecnicos] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [SistemaTecnicos] SET  READ_WRITE
GO
ALTER DATABASE [SistemaTecnicos] SET RECOVERY FULL
GO
ALTER DATABASE [SistemaTecnicos] SET  MULTI_USER
GO
ALTER DATABASE [SistemaTecnicos] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [SistemaTecnicos] SET DB_CHAINING OFF
GO
EXEC sys.sp_db_vardecimal_storage_format N'SistemaTecnicos', N'ON'
GO
USE [SistemaTecnicos]
GO
/****** Object:  Table [dbo].[ROL]    Script Date: 03/25/2013 20:19:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ROL](
	[ID] [int] NOT NULL,
	[Nombre] [varchar](50) NOT NULL,
 CONSTRAINT [PK_ROL] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[LOCALIZACION]    Script Date: 03/25/2013 20:19:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[LOCALIZACION](
	[ID] [int] NOT NULL,
	[Nombre] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[ESTADO]    Script Date: 03/25/2013 20:19:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ESTADO](
	[ID] [int] NOT NULL,
	[Nombre] [varchar](50) NOT NULL,
 CONSTRAINT [PK_ESTADO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[USUARIO]    Script Date: 03/25/2013 20:19:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[USUARIO](
	[Documento] [int] NOT NULL,
	[Nombre] [varchar](50) NOT NULL,
	[Password] [varchar](50) NOT NULL,
	[ID_Rol] [int] NOT NULL,
	[ID_Localizacion] [int] NOT NULL,
 CONSTRAINT [PK_USUARIO] PRIMARY KEY CLUSTERED 
(
	[Documento] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  StoredProcedure [dbo].[UsuarioGet]    Script Date: 03/25/2013 20:19:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[UsuarioGet] 
	@documento int
AS
BEGIN
	SELECT * FROM USUARIO 
	WHERE documento = @documento
END
GO
/****** Object:  Table [dbo].[COORDINADOR]    Script Date: 03/25/2013 20:19:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COORDINADOR](
	[Documento] [int] NOT NULL,
 CONSTRAINT [PK_COORDINADOR] PRIMARY KEY CLUSTERED 
(
	[Documento] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CLIENTE]    Script Date: 03/25/2013 20:19:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CLIENTE](
	[Documento] [int] NOT NULL,
	[Direccion] [varchar](50) NOT NULL,
	[FechaExpDocumento] [varchar](50) NOT NULL,
 CONSTRAINT [PK_CLIENTE] PRIMARY KEY CLUSTERED 
(
	[Documento] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[AGENTE]    Script Date: 03/25/2013 20:19:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[AGENTE](
	[Documento] [int] NOT NULL,
	[Especializacion] [varchar](50) NOT NULL,
	[ID_Coordinador] [int] NOT NULL,
 CONSTRAINT [PK_AGENTE] PRIMARY KEY CLUSTERED 
(
	[Documento] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IX_AGENTE] ON [dbo].[AGENTE] 
(
	[Documento] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TAREA]    Script Date: 03/25/2013 20:19:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TAREA](
	[ID] [int] NOT NULL,
	[ID_Cliente] [int] NOT NULL,
	[ID_Agente] [int] NOT NULL,
	[Descripcion] [varchar](50) NOT NULL,
	[ID_Estado] [int] NOT NULL,
	[FechaInicio] [datetime] NOT NULL,
	[FechaFinalizacion] [datetime] NOT NULL,
	[FechaEsperadaInit] [datetime] NOT NULL,
	[FechaEsperadaFin] [datetime] NOT NULL,
	[FechaRadicacion] [datetime] NOT NULL,
	[Comentario] [varchar](50) NOT NULL,
	[Direccion] [varchar](50) NOT NULL,
	[ID_Localizacion] [int] NOT NULL,
 CONSTRAINT [PK_TAREA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  ForeignKey [FK_USUARIO_LOCALIZACION]    Script Date: 03/25/2013 20:19:02 ******/
ALTER TABLE [dbo].[USUARIO]  WITH CHECK ADD  CONSTRAINT [FK_USUARIO_LOCALIZACION] FOREIGN KEY([ID_Localizacion])
REFERENCES [dbo].[LOCALIZACION] ([ID])
GO
ALTER TABLE [dbo].[USUARIO] CHECK CONSTRAINT [FK_USUARIO_LOCALIZACION]
GO
/****** Object:  ForeignKey [FK_USUARIO_ROL]    Script Date: 03/25/2013 20:19:02 ******/
ALTER TABLE [dbo].[USUARIO]  WITH CHECK ADD  CONSTRAINT [FK_USUARIO_ROL] FOREIGN KEY([ID_Rol])
REFERENCES [dbo].[ROL] ([ID])
GO
ALTER TABLE [dbo].[USUARIO] CHECK CONSTRAINT [FK_USUARIO_ROL]
GO
/****** Object:  ForeignKey [FK_COORDINADOR_USUARIO]    Script Date: 03/25/2013 20:19:03 ******/
ALTER TABLE [dbo].[COORDINADOR]  WITH CHECK ADD  CONSTRAINT [FK_COORDINADOR_USUARIO] FOREIGN KEY([Documento])
REFERENCES [dbo].[USUARIO] ([Documento])
GO
ALTER TABLE [dbo].[COORDINADOR] CHECK CONSTRAINT [FK_COORDINADOR_USUARIO]
GO
/****** Object:  ForeignKey [FK_CLIENTE_USUARIO]    Script Date: 03/25/2013 20:19:03 ******/
ALTER TABLE [dbo].[CLIENTE]  WITH CHECK ADD  CONSTRAINT [FK_CLIENTE_USUARIO] FOREIGN KEY([Documento])
REFERENCES [dbo].[USUARIO] ([Documento])
GO
ALTER TABLE [dbo].[CLIENTE] CHECK CONSTRAINT [FK_CLIENTE_USUARIO]
GO
/****** Object:  ForeignKey [FK_AGENTE_COORDINADOR]    Script Date: 03/25/2013 20:19:03 ******/
ALTER TABLE [dbo].[AGENTE]  WITH CHECK ADD  CONSTRAINT [FK_AGENTE_COORDINADOR] FOREIGN KEY([ID_Coordinador])
REFERENCES [dbo].[COORDINADOR] ([Documento])
GO
ALTER TABLE [dbo].[AGENTE] CHECK CONSTRAINT [FK_AGENTE_COORDINADOR]
GO
/****** Object:  ForeignKey [FK_AGENTE_USUARIO]    Script Date: 03/25/2013 20:19:03 ******/
ALTER TABLE [dbo].[AGENTE]  WITH CHECK ADD  CONSTRAINT [FK_AGENTE_USUARIO] FOREIGN KEY([Documento])
REFERENCES [dbo].[USUARIO] ([Documento])
GO
ALTER TABLE [dbo].[AGENTE] CHECK CONSTRAINT [FK_AGENTE_USUARIO]
GO
/****** Object:  ForeignKey [FK_TAREA_AGENTE]    Script Date: 03/25/2013 20:19:03 ******/
ALTER TABLE [dbo].[TAREA]  WITH CHECK ADD  CONSTRAINT [FK_TAREA_AGENTE] FOREIGN KEY([ID_Agente])
REFERENCES [dbo].[AGENTE] ([Documento])
GO
ALTER TABLE [dbo].[TAREA] CHECK CONSTRAINT [FK_TAREA_AGENTE]
GO
/****** Object:  ForeignKey [FK_TAREA_CLIENTE]    Script Date: 03/25/2013 20:19:03 ******/
ALTER TABLE [dbo].[TAREA]  WITH CHECK ADD  CONSTRAINT [FK_TAREA_CLIENTE] FOREIGN KEY([ID_Cliente])
REFERENCES [dbo].[CLIENTE] ([Documento])
GO
ALTER TABLE [dbo].[TAREA] CHECK CONSTRAINT [FK_TAREA_CLIENTE]
GO
/****** Object:  ForeignKey [FK_TAREA_ESTADO]    Script Date: 03/25/2013 20:19:03 ******/
ALTER TABLE [dbo].[TAREA]  WITH CHECK ADD  CONSTRAINT [FK_TAREA_ESTADO] FOREIGN KEY([ID_Estado])
REFERENCES [dbo].[ESTADO] ([ID])
GO
ALTER TABLE [dbo].[TAREA] CHECK CONSTRAINT [FK_TAREA_ESTADO]
GO
/****** Object:  ForeignKey [FK_TAREA_LOCALIZACION]    Script Date: 03/25/2013 20:19:03 ******/
ALTER TABLE [dbo].[TAREA]  WITH CHECK ADD  CONSTRAINT [FK_TAREA_LOCALIZACION] FOREIGN KEY([ID_Localizacion])
REFERENCES [dbo].[LOCALIZACION] ([ID])
GO
ALTER TABLE [dbo].[TAREA] CHECK CONSTRAINT [FK_TAREA_LOCALIZACION]
GO