USE [master]
GO
/****** Object:  Database [SistemaTecnicos]    Script Date: 03/25/2013 20:19:01 ******/
CREATE DATABASE [SistemaTecnicos] ON  PRIMARY 
( NAME = N'SistemaTecnicos', FILENAME = N'C:\SistemaTecnicos.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SistemaTecnicos_log', FILENAME = N'C:\SistemaTecnicos_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [SistemaTecnicos] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SistemaTecnicos].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SistemaTecnicos] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [SistemaTecnicos] SET ANSI_NULLS OFF
GO
ALTER DATABASE [SistemaTecnicos] SET ANSI_PADDING OFF
GO
ALTER DATABASE [SistemaTecnicos] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [SistemaTecnicos] SET ARITHABORT OFF
GO
ALTER DATABASE [SistemaTecnicos] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [SistemaTecnicos] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [SistemaTecnicos] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [SistemaTecnicos] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [SistemaTecnicos] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [SistemaTecnicos] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [SistemaTecnicos] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [SistemaTecnicos] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [SistemaTecnicos] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [SistemaTecnicos] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [SistemaTecnicos] SET  DISABLE_BROKER
GO
ALTER DATABASE [SistemaTecnicos] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [SistemaTecnicos] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [SistemaTecnicos] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [SistemaTecnicos] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [SistemaTecnicos] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [SistemaTecnicos] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [SistemaTecnicos] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [SistemaTecnicos] SET  READ_WRITE
GO
ALTER DATABASE [SistemaTecnicos] SET RECOVERY FULL
GO
ALTER DATABASE [SistemaTecnicos] SET  MULTI_USER
GO
ALTER DATABASE [SistemaTecnicos] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [SistemaTecnicos] SET DB_CHAINING OFF
GO
EXEC sys.sp_db_vardecimal_storage_format N'SistemaTecnicos', N'ON'
GO
USE [SistemaTecnicos]
GO
/****** Object:  Table [dbo].[ROL]    Script Date: 03/25/2013 20:19:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ROL](
	[ID] [int] NOT NULL,
	[Name] [varchar](50) NOT NULL,
 CONSTRAINT [PK_ROL] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[LOCALIZATION]    Script Date: 03/25/2013 20:19:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[LOCALIZATION](
	[ID] [int] NOT NULL,
	[Name] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[STATE]    Script Date: 03/25/2013 20:19:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[STATE](
	[ID] [int] NOT NULL,
	[Name] [varchar](50) NOT NULL,
 CONSTRAINT [PK_STATE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[USER]    Script Date: 03/25/2013 20:19:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[USER](
	[Document] [int] NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Password] [varchar](50) NOT NULL,
	[ID_Rol] [int] NOT NULL,
	[ID_Localization] [int] NOT NULL,
 CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED 
(
	[Document] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  StoredProcedure [dbo].[UserGet]    Script Date: 03/25/2013 20:19:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[UserGet] 
	@Document int
AS
BEGIN
	SELECT * FROM USER 
	WHERE Document = @Document
END
GO
/****** Object:  Table [dbo].[MANAGER]    Script Date: 03/25/2013 20:19:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MANAGER](
	[Document] [int] NOT NULL,
 CONSTRAINT [PK_MANAGER] PRIMARY KEY CLUSTERED 
(
	[Document] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CLIENT]    Script Date: 03/25/2013 20:19:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CLIENT](
	[Document] [int] NOT NULL,
	[Address] [varchar](50) NOT NULL,
	[DateExpDocument] [varchar](50) NOT NULL,
 CONSTRAINT [PK_CLIENT] PRIMARY KEY CLUSTERED 
(
	[Document] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[AGENT]    Script Date: 03/25/2013 20:19:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[AGENT](
	[Document] [int] NOT NULL,
	[Especializacion] [varchar](50) NOT NULL,
	[ID_Manager] [int] NOT NULL,
 CONSTRAINT [PK_AGENT] PRIMARY KEY CLUSTERED 
(
	[Document] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IX_AGENT] ON [dbo].[AGENT] 
(
	[Document] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TASK]    Script Date: 03/25/2013 20:19:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TASK](
	[ID] [int] NOT NULL,
	[ID_Cliente] [int] NOT NULL,
	[ID_Agente] [int] NOT NULL,
	[Descripcion] [varchar](50) NOT NULL,
	[ID_Estado] [int] NOT NULL,
	[FechaInicio] [datetime] NOT NULL,
	[FechaFinalizacion] [datetime] NOT NULL,
	[FechaEsperadaInit] [datetime] NOT NULL,
	[FechaEsperadaFin] [datetime] NOT NULL,
	[FechaRadicacion] [datetime] NOT NULL,
	[Comentario] [varchar](50) NOT NULL,
	[Address] [varchar](50) NOT NULL,
	[ID_Localization] [int] NOT NULL,
 CONSTRAINT [PK_TASK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  ForeignKey [FK_USER_LOCALIZATION]    Script Date: 03/25/2013 20:19:02 ******/
ALTER TABLE [dbo].[USER]  WITH CHECK ADD  CONSTRAINT [FK_USER_LOCALIZATION] FOREIGN KEY([ID_Localization])
REFERENCES [dbo].[LOCALIZATION] ([ID])
GO
ALTER TABLE [dbo].[USER] CHECK CONSTRAINT [FK_USER_LOCALIZATION]
GO
/****** Object:  ForeignKey [FK_USER_ROL]    Script Date: 03/25/2013 20:19:02 ******/
ALTER TABLE [dbo].[USER]  WITH CHECK ADD  CONSTRAINT [FK_USER_ROL] FOREIGN KEY([ID_Rol])
REFERENCES [dbo].[ROL] ([ID])
GO
ALTER TABLE [dbo].[USER] CHECK CONSTRAINT [FK_USER_ROL]
GO
/****** Object:  ForeignKey [FK_MANAGER_USER]    Script Date: 03/25/2013 20:19:03 ******/
ALTER TABLE [dbo].[MANAGER]  WITH CHECK ADD  CONSTRAINT [FK_MANAGER_USER] FOREIGN KEY([Document])
REFERENCES [dbo].[USER] ([Document])
GO
ALTER TABLE [dbo].[MANAGER] CHECK CONSTRAINT [FK_MANAGER_USER]
GO
/****** Object:  ForeignKey [FK_CLIENT_USER]    Script Date: 03/25/2013 20:19:03 ******/
ALTER TABLE [dbo].[CLIENT]  WITH CHECK ADD  CONSTRAINT [FK_CLIENT_USER] FOREIGN KEY([Document])
REFERENCES [dbo].[USER] ([Document])
GO
ALTER TABLE [dbo].[CLIENT] CHECK CONSTRAINT [FK_CLIENT_USER]
GO
/****** Object:  ForeignKey [FK_AGENT_MANAGER]    Script Date: 03/25/2013 20:19:03 ******/
ALTER TABLE [dbo].[AGENT]  WITH CHECK ADD  CONSTRAINT [FK_AGENT_MANAGER] FOREIGN KEY([ID_Manager])
REFERENCES [dbo].[MANAGER] ([Document])
GO
ALTER TABLE [dbo].[AGENT] CHECK CONSTRAINT [FK_AGENT_MANAGER]
GO
/****** Object:  ForeignKey [FK_AGENT_USER]    Script Date: 03/25/2013 20:19:03 ******/
ALTER TABLE [dbo].[AGENT]  WITH CHECK ADD  CONSTRAINT [FK_AGENT_USER] FOREIGN KEY([Document])
REFERENCES [dbo].[USER] ([Document])
GO
ALTER TABLE [dbo].[AGENT] CHECK CONSTRAINT [FK_AGENT_USER]
GO
/****** Object:  ForeignKey [FK_TASK_AGENT]    Script Date: 03/25/2013 20:19:03 ******/
ALTER TABLE [dbo].[TASK]  WITH CHECK ADD  CONSTRAINT [FK_TASK_AGENT] FOREIGN KEY([ID_Agente])
REFERENCES [dbo].[AGENT] ([Document])
GO
ALTER TABLE [dbo].[TASK] CHECK CONSTRAINT [FK_TASK_AGENT]
GO
/****** Object:  ForeignKey [FK_TASK_CLIENT]    Script Date: 03/25/2013 20:19:03 ******/
ALTER TABLE [dbo].[TASK]  WITH CHECK ADD  CONSTRAINT [FK_TASK_CLIENT] FOREIGN KEY([ID_Cliente])
REFERENCES [dbo].[CLIENT] ([Document])
GO
ALTER TABLE [dbo].[TASK] CHECK CONSTRAINT [FK_TASK_CLIENT]
GO
/****** Object:  ForeignKey [FK_TASK_STATE]    Script Date: 03/25/2013 20:19:03 ******/
ALTER TABLE [dbo].[TASK]  WITH CHECK ADD  CONSTRAINT [FK_TASK_STATE] FOREIGN KEY([ID_Estado])
REFERENCES [dbo].[STATE] ([ID])
GO
ALTER TABLE [dbo].[TASK] CHECK CONSTRAINT [FK_TASK_STATE]
GO
/****** Object:  ForeignKey [FK_TASK_LOCALIZATION]    Script Date: 03/25/2013 20:19:03 ******/
ALTER TABLE [dbo].[TASK]  WITH CHECK ADD  CONSTRAINT [FK_TASK_LOCALIZATION] FOREIGN KEY([ID_Localization])
REFERENCES [dbo].[LOCALIZATION] ([ID])
GO
ALTER TABLE [dbo].[TASK] CHECK CONSTRAINT [FK_TASK_LOCALIZATION]
GO